name: Deploy to Github Pages

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install Node versions
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install
        run: npm i

      - name: Linter
        run: npm run lint

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: lint

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - run: npm i

      - name: Configure GH pages
        uses: actions/configure-pages@v3

      - name: Build
        run: npm run build

      - name: Uploading Artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist/

      - name: Deploy to GH pages
        uses: actions/deploy-pages@v1
        id: deployment
